algoritmo calc

var 
    N1: inteiro
    N2: inteiro
    soma: inteiro
    sub: inteiro
    mul: inteiro
    divs: inteiro

inicio

    escreva("Digite o primeiro número: ")
    leia(N1)
    escreva("Digite o segundo número: ")
    leia(N2)

    soma <- N1 + N2
    sub <- N1 - N2
    mul <- N1 * N2
    divs <- N1 / N2


    escreval("A soma dos dois número é: ", soma)
    escreval("A subtração dos dois número é: ", sub)
    escreval("A multiplicação dos dois número é: ", mul)
    escreval("A divisão dos dois número é: ", divs)

fimalgoritmo